### ISSUE TITLE
Upload multiple media

### ISSUE THREAD

**Issue by har2008preet** [payloadcms/public-demo#10]
Hi,

Is it possible to attach multiple medias to a field?

**Comment by jmikrut** [comment]
Hey @har2008preet — right now, you would want to use an Array field and put an upload within each row of the Array field. But, this is on our radar to build. This is actually more of a discussion than an issue, so I'm going to close this one, but if you have any other questions, check out the Payload core Discussions because I believe there are a few conversations about this already there!
